# 8.3.捕获异常

- 通过捕获异常对其进行处理
- 通过`try/except`语句捕获指定类型的异常

```python3
try:
    # Critical Code(
except( ExceptionClass|(ExceptionClass(, ExceptionClass)*)( as exception)?)?:
    # Exception Handler)*(
else:
    # Planned Handler)?(
finally:
    # Cleanning Up)?
```

- 异常对象从`raise`语句向外传播到主调函数
- 如果没有被捕获, 异常将向程序的最顶层传播
- 可以在主调函数中使用`try/except`语句来捕获由被调函数引发的异常
- 捕获并抑制异常: `except ExceptionClass: pass`

## 1. 不提供参数

- 与用户交互时, 因处理并抑制异常并避免程序退出; 与程序交互时, 应继续传播而非抑制异常
- 捕获异常后, 可以在`except`子句中重新引发异常, 使其向上传播
    - 使用不带参数的raise语句重新引发导致进入except子句的异常: `raise`
    - 使用带参数的raise语句引发其他异常: `raise ExceptionClass`, `raise exception_object`
        - 此时, 导致进入except子句的异常将被作为异常上下文存储起来, 并出现在最终的错误消息中, 表示处理原异常时出现了另一个异常
        - 多层异常打印时, 最外层异常打印在末尾. 一般仅处理最外层异常即可
    - 使用`raise/from`语句显式指定异常上下文, 或使用`None`来禁用上下文: `raise (ExceptionClass|exception_object) from (ExceptionClass|exception_object|None)`

## 2. 多个except子句

- 一个`try/except`语句中可以包含多个`except`子句, 来分别处理不同异常类型的异常对象
- 异常处理比if语句检查可读性更强

## 3. 一箭双雕

- 通过为`except`子句提供异常类型元组来在一个`except`子句中捕获多种异常
- 注意: 异常类型元组两边的圆括号必不可少, 至关重要

## 4. 捕获对象

- 通过为`except`子句添加`as`子句, 来在`except`子句中访问异常对象
- 可用于记录错误并让程序继续运行

## 5. Exception Object

- `str(exception)`: Exception message

## 6. 一网打尽

- 通过在`except`子句中不指定任何异常类 (此时不能添加`as`子句) 来捕获任何异常类的实例
- 注意: 这样捕获所有的异常很危险, 这将隐藏没有考虑到的异常事件, 包括`Ctrl-C`与`sys.exit`终止程序的尝试. 对于没有预料到的异常事件, 与其捕获和抑制, 不如让程序立即崩溃来知晓原因
- 更好的选择: 通过`except Exception as exception:`来捕获异常并对异常对象进行检查
- 注意: 这不会捕获不是从Exception派生而来的异常, 如从Exception的超类BaseException派生而来的SystemExit和KeyboardInterrupt

## 7. 万事大吉时

- 可以给`try/except`语句添加一个`else`子句. `else`子句只会在`try`语句块正常结束而没有出现异常时执行, 不会在出现异常并捕获和处理后执行

重试成例:

```python3
while True:
    try:
        # Critical Code
    except Exception as exception:
        # Exception Handler
    else:
        break
```

只有当没有引发异常时, 才会结束循环; 只要出现异常, 就会重试

## 8. 最后

- `finally`子句: 不论`try`语句中是否发生异常, `return`或`sys.exit()`, 都将执行`finally`子句再继续执行后续程序, 向上抛出异常或结束程序
- 可用于执行清理工作, 比如确保文件或网络套接字得以关闭
